### ISSUE TITLE
Add searchbar to more screens

### ISSUE THREAD

**Issue by ItsProfessional** [Antikyth/searchable#20]
I recently switched from [Enhanced Searchability](enhanced-searchability) to this mod. That mod also added search bars to the following screens

- Resource pack selector screen
- Datapack selector screen

I'd like if a search bar could be added for these screens in Searchable

**Comment by Antikyth** [comment]
Those are good suggestions!  I'll add support for those when I have time, hopefully next week (week starting Monday, tomorrow for me).

**Comment by Antikyth** [comment]
Added this now, will be out in `0.2.0` soon :)

**Comment by Antikyth** [comment]
https://modrinth.com/mod/searchable/version/0.2.1+1.20.1
